name: Simple Deploy Docs
on:
  push:
    branches: [main] # 推送 main 分支触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: name: Simple Deploy Docs
on:
  push:
    branches: [main] # 推送 main 分支触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2 # 使用官方的 checkout Action
name: Simple Deploy Docs
on:name: Simple Deploy Docs
on:
  push:
    branches: [main] # 推送 main 分支触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2 # 使用检出代码的 Action

  push:
    branches: [main] # 推送 main 分支触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2 # 使用检出代码的 Action
ame: Simple Deploy Docs
on:
  push:
    branches: [main] # 推送 main 分支触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
name: Simple Deploy Docs
on:
  push:
    branches: [main] # 推送 main 分支触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
actions/checkout@v3name: Simple Deploy Docs
on:
  push:
    branches: [main] # 推送 main 分支触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 配置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装 pnpm
        run: npm install -g pnpm


      - name: 配置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm install

      - name: 构建文档
        run: npm run docs:build # 确保 package.json 有这个脚本

      - name: 部署到 Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/.vitepress/dist # 文档输出目录77